#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["./apis/scage-scale-api/SCAGEScale/SCAGEScale.Api/SCAGEScale.Api.csproj", "SCAGEScale/SCAGEScale.Api/"]
COPY ["./apis/scage-scale-api/SCAGEScale/SCAGEScale.Application/SCAGEScale.Application.csproj", "SCAGEScale/SCAGEScale.Application/"]
COPY ["./apis/scage-scale-api/SCAGEScale/SCAGEScale.Infrastructure/SCAGEScale.Infrastructure.csproj", "SCAGEScale/SCAGEScale.Infrastructure/"]
RUN dotnet restore "SCAGEScale/SCAGEScale.Api/SCAGEScale.Api.csproj"
COPY . .
WORKDIR "/src/apis/scage-scale-api/SCAGEScale/SCAGEScale.Api"
RUN dotnet build "SCAGEScale.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SCAGEScale.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SCAGEScale.Api.dll"]